### PR TITLE
ENH - start of test framework for repo

### PR DESCRIPTION
**Pull request by schoffelen**
here's a first attempt for a unit test function

### CODE REVIEW

**Comment by schoffelen** [comment]
note that this test will fail, because of the fact that the constants definition file is out-of-sync with the m-file codebase (or there are typos in the codebase)

**Comment by schoffelen** [comment]
This PR links to the discussion here: https://github.com/mne-tools/mne-matlab/pull/25

It's still a bit open ended, but it now adds a small number of functions to do some basic testing on reading and writing off fiff-files, only using the relatively simple test_raw.fif file (and it's colleagues in the test folder). So the tests don't deal yet with the fancy stuff chaninfo, projectors, compensation matrices etc. 

I hope however to move this forward, so that I can move on to working on the other mentioned pull request (unit tests to be added there before it can be merged), so that FieldTrip can be brought in sync again with this codebase.

So, @larsoner would you be good for merging this PR for now, and for me to take some next steps? Oh, and as I mentioned before, I don't mind taking a bit responsibility for this repo, in which case I might be considered to get a little bit more github rights (merging etc :) ).

PS: there may be changes more on the way, since I have some proposed changes to speed up one-tag-per-datasample fif-file handling (as are the files currently produced by the FieldLine OPM acquisition system), which is currently only in a FieldTrip PR, not as it should be

**Review by larsoner — APPROVED** [review]
Looks like a good start and CIs appear to have run the tests, thanks @schoffelen !

**Comment by schoffelen** [comment]
thanks @larsoner !

**Pull request merged**
