### PR TITLE
WIP: read/write epochs

### PR DESCRIPTION
**Pull request by mluessi**
WIP: Reading epochs in Matlab works, writing function and comparison with MNE-Python to follow.

### CODE REVIEW

**Comment by nbara** [comment]
Hi, I'm struggling to read MNE epochs in fif format in matlab using ft_read_data()

I replaced the contents of `external/mne` in fieldtrip with the latest version of this repo...

`Reference to non-existent field 'FIFFB_MNE_EPOCHS'.

Error in fiff_read_epochs (line 43)
ep = fiff_dir_tree_find(meas, FIFF.FIFFB_MNE_EPOCHS);

Error in ft_read_header (line 1697)
        epochs = fiff_read_epochs(filename);

Error in ft_read_data (line 200)
  hdr = ft_read_header(filename, 'headerformat',
  headerformat, 'chanindx', chanindx, 'checkmaxfilter',
  checkmaxfilter);`

Do you have any idea what could have gone wrong?

**Comment by agramfort** [comment]
with what version of mne did you save the file?

**Comment by nbara** [comment]
Sorry @agramfort, I actually had another fieldtrip version in my path. All solved now/deleted my comment. :)

FWIW, I don't think the latest fieldtrip version inlcudes your latest commits to this repo, I had to manually replace `fieldtrip/external/mne` (maybe @robertoostenveld will be interested?)

**Comment by agramfort** [comment]
I think it does. Please close if it the case.

**Pull request merged**
